/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZiabotRouteImport } from './routes/ziabot'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KnowledgeArenaRouteImport } from './routes/knowledge-arena'
import { Route as FunGamesRouteImport } from './routes/fun-games'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as BossBattleRouteImport } from './routes/boss-battle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZiabotPracticeRouteImport } from './routes/ziabot.practice'
import { Route as ZiabotNotesRouteImport } from './routes/ziabot.notes'
import { Route as ZiabotFlashcardsRouteImport } from './routes/ziabot.flashcards'
import { Route as KnowledgeArenaMatchRouteImport } from './routes/knowledge-arena.match'
import { Route as KnowledgeArenaLobbyRouteImport } from './routes/knowledge-arena.lobby'
import { Route as FunGamesPatternRouteImport } from './routes/fun-games.pattern'
import { Route as FunGamesMemoryRouteImport } from './routes/fun-games.memory'
import { Route as FunGamesLogicRouteImport } from './routes/fun-games.logic'
import { Route as ExploreSubjectIdRouteImport } from './routes/explore.$subjectId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CreatorExplainRouteImport } from './routes/creator.explain'
import { Route as BossBattleBattleIdRouteImport } from './routes/boss-battle.$battleId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const ZiabotRoute = ZiabotRouteImport.update({
  id: '/ziabot',
  path: '/ziabot',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeArenaRoute = KnowledgeArenaRouteImport.update({
  id: '/knowledge-arena',
  path: '/knowledge-arena',
  getParentRoute: () => rootRouteImport,
} as any)
const FunGamesRoute = FunGamesRouteImport.update({
  id: '/fun-games',
  path: '/fun-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const BossBattleRoute = BossBattleRouteImport.update({
  id: '/boss-battle',
  path: '/boss-battle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiabotPracticeRoute = ZiabotPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => ZiabotRoute,
} as any)
const ZiabotNotesRoute = ZiabotNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ZiabotRoute,
} as any)
const ZiabotFlashcardsRoute = ZiabotFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => ZiabotRoute,
} as any)
const KnowledgeArenaMatchRoute = KnowledgeArenaMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => KnowledgeArenaRoute,
} as any)
const KnowledgeArenaLobbyRoute = KnowledgeArenaLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => KnowledgeArenaRoute,
} as any)
const FunGamesPatternRoute = FunGamesPatternRouteImport.update({
  id: '/pattern',
  path: '/pattern',
  getParentRoute: () => FunGamesRoute,
} as any)
const FunGamesMemoryRoute = FunGamesMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => FunGamesRoute,
} as any)
const FunGamesLogicRoute = FunGamesLogicRouteImport.update({
  id: '/logic',
  path: '/logic',
  getParentRoute: () => FunGamesRoute,
} as any)
const ExploreSubjectIdRoute = ExploreSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => ExploreRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorExplainRoute = CreatorExplainRouteImport.update({
  id: '/creator/explain',
  path: '/creator/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const BossBattleBattleIdRoute = BossBattleBattleIdRouteImport.update({
  id: '/$battleId',
  path: '/$battleId',
  getParentRoute: () => BossBattleRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boss-battle': typeof BossBattleRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/fun-games': typeof FunGamesRouteWithChildren
  '/knowledge-arena': typeof KnowledgeArenaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/ziabot': typeof ZiabotRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/boss-battle/$battleId': typeof BossBattleBattleIdRoute
  '/creator/explain': typeof CreatorExplainRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/explore/$subjectId': typeof ExploreSubjectIdRoute
  '/fun-games/logic': typeof FunGamesLogicRoute
  '/fun-games/memory': typeof FunGamesMemoryRoute
  '/fun-games/pattern': typeof FunGamesPatternRoute
  '/knowledge-arena/lobby': typeof KnowledgeArenaLobbyRoute
  '/knowledge-arena/match': typeof KnowledgeArenaMatchRoute
  '/ziabot/flashcards': typeof ZiabotFlashcardsRoute
  '/ziabot/notes': typeof ZiabotNotesRoute
  '/ziabot/practice': typeof ZiabotPracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boss-battle': typeof BossBattleRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/fun-games': typeof FunGamesRouteWithChildren
  '/knowledge-arena': typeof KnowledgeArenaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/ziabot': typeof ZiabotRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/boss-battle/$battleId': typeof BossBattleBattleIdRoute
  '/creator/explain': typeof CreatorExplainRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/explore/$subjectId': typeof ExploreSubjectIdRoute
  '/fun-games/logic': typeof FunGamesLogicRoute
  '/fun-games/memory': typeof FunGamesMemoryRoute
  '/fun-games/pattern': typeof FunGamesPatternRoute
  '/knowledge-arena/lobby': typeof KnowledgeArenaLobbyRoute
  '/knowledge-arena/match': typeof KnowledgeArenaMatchRoute
  '/ziabot/flashcards': typeof ZiabotFlashcardsRoute
  '/ziabot/notes': typeof ZiabotNotesRoute
  '/ziabot/practice': typeof ZiabotPracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boss-battle': typeof BossBattleRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/fun-games': typeof FunGamesRouteWithChildren
  '/knowledge-arena': typeof KnowledgeArenaRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/ziabot': typeof ZiabotRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/boss-battle/$battleId': typeof BossBattleBattleIdRoute
  '/creator/explain': typeof CreatorExplainRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/explore/$subjectId': typeof ExploreSubjectIdRoute
  '/fun-games/logic': typeof FunGamesLogicRoute
  '/fun-games/memory': typeof FunGamesMemoryRoute
  '/fun-games/pattern': typeof FunGamesPatternRoute
  '/knowledge-arena/lobby': typeof KnowledgeArenaLobbyRoute
  '/knowledge-arena/match': typeof KnowledgeArenaMatchRoute
  '/ziabot/flashcards': typeof ZiabotFlashcardsRoute
  '/ziabot/notes': typeof ZiabotNotesRoute
  '/ziabot/practice': typeof ZiabotPracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boss-battle'
    | '/downloads'
    | '/explore'
    | '/fun-games'
    | '/knowledge-arena'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/ziabot'
    | '/auth/login'
    | '/auth/signup'
    | '/boss-battle/$battleId'
    | '/creator/explain'
    | '/demo/tanstack-query'
    | '/explore/$subjectId'
    | '/fun-games/logic'
    | '/fun-games/memory'
    | '/fun-games/pattern'
    | '/knowledge-arena/lobby'
    | '/knowledge-arena/match'
    | '/ziabot/flashcards'
    | '/ziabot/notes'
    | '/ziabot/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boss-battle'
    | '/downloads'
    | '/explore'
    | '/fun-games'
    | '/knowledge-arena'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/ziabot'
    | '/auth/login'
    | '/auth/signup'
    | '/boss-battle/$battleId'
    | '/creator/explain'
    | '/demo/tanstack-query'
    | '/explore/$subjectId'
    | '/fun-games/logic'
    | '/fun-games/memory'
    | '/fun-games/pattern'
    | '/knowledge-arena/lobby'
    | '/knowledge-arena/match'
    | '/ziabot/flashcards'
    | '/ziabot/notes'
    | '/ziabot/practice'
  id:
    | '__root__'
    | '/'
    | '/boss-battle'
    | '/downloads'
    | '/explore'
    | '/fun-games'
    | '/knowledge-arena'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/ziabot'
    | '/auth/login'
    | '/auth/signup'
    | '/boss-battle/$battleId'
    | '/creator/explain'
    | '/demo/tanstack-query'
    | '/explore/$subjectId'
    | '/fun-games/logic'
    | '/fun-games/memory'
    | '/fun-games/pattern'
    | '/knowledge-arena/lobby'
    | '/knowledge-arena/match'
    | '/ziabot/flashcards'
    | '/ziabot/notes'
    | '/ziabot/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BossBattleRoute: typeof BossBattleRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FunGamesRoute: typeof FunGamesRouteWithChildren
  KnowledgeArenaRoute: typeof KnowledgeArenaRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  ZiabotRoute: typeof ZiabotRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CreatorExplainRoute: typeof CreatorExplainRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ziabot': {
      id: '/ziabot'
      path: '/ziabot'
      fullPath: '/ziabot'
      preLoaderRoute: typeof ZiabotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-arena': {
      id: '/knowledge-arena'
      path: '/knowledge-arena'
      fullPath: '/knowledge-arena'
      preLoaderRoute: typeof KnowledgeArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-games': {
      id: '/fun-games'
      path: '/fun-games'
      fullPath: '/fun-games'
      preLoaderRoute: typeof FunGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss-battle': {
      id: '/boss-battle'
      path: '/boss-battle'
      fullPath: '/boss-battle'
      preLoaderRoute: typeof BossBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziabot/practice': {
      id: '/ziabot/practice'
      path: '/practice'
      fullPath: '/ziabot/practice'
      preLoaderRoute: typeof ZiabotPracticeRouteImport
      parentRoute: typeof ZiabotRoute
    }
    '/ziabot/notes': {
      id: '/ziabot/notes'
      path: '/notes'
      fullPath: '/ziabot/notes'
      preLoaderRoute: typeof ZiabotNotesRouteImport
      parentRoute: typeof ZiabotRoute
    }
    '/ziabot/flashcards': {
      id: '/ziabot/flashcards'
      path: '/flashcards'
      fullPath: '/ziabot/flashcards'
      preLoaderRoute: typeof ZiabotFlashcardsRouteImport
      parentRoute: typeof ZiabotRoute
    }
    '/knowledge-arena/match': {
      id: '/knowledge-arena/match'
      path: '/match'
      fullPath: '/knowledge-arena/match'
      preLoaderRoute: typeof KnowledgeArenaMatchRouteImport
      parentRoute: typeof KnowledgeArenaRoute
    }
    '/knowledge-arena/lobby': {
      id: '/knowledge-arena/lobby'
      path: '/lobby'
      fullPath: '/knowledge-arena/lobby'
      preLoaderRoute: typeof KnowledgeArenaLobbyRouteImport
      parentRoute: typeof KnowledgeArenaRoute
    }
    '/fun-games/pattern': {
      id: '/fun-games/pattern'
      path: '/pattern'
      fullPath: '/fun-games/pattern'
      preLoaderRoute: typeof FunGamesPatternRouteImport
      parentRoute: typeof FunGamesRoute
    }
    '/fun-games/memory': {
      id: '/fun-games/memory'
      path: '/memory'
      fullPath: '/fun-games/memory'
      preLoaderRoute: typeof FunGamesMemoryRouteImport
      parentRoute: typeof FunGamesRoute
    }
    '/fun-games/logic': {
      id: '/fun-games/logic'
      path: '/logic'
      fullPath: '/fun-games/logic'
      preLoaderRoute: typeof FunGamesLogicRouteImport
      parentRoute: typeof FunGamesRoute
    }
    '/explore/$subjectId': {
      id: '/explore/$subjectId'
      path: '/$subjectId'
      fullPath: '/explore/$subjectId'
      preLoaderRoute: typeof ExploreSubjectIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/explain': {
      id: '/creator/explain'
      path: '/creator/explain'
      fullPath: '/creator/explain'
      preLoaderRoute: typeof CreatorExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss-battle/$battleId': {
      id: '/boss-battle/$battleId'
      path: '/$battleId'
      fullPath: '/boss-battle/$battleId'
      preLoaderRoute: typeof BossBattleBattleIdRouteImport
      parentRoute: typeof BossBattleRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BossBattleRouteChildren {
  BossBattleBattleIdRoute: typeof BossBattleBattleIdRoute
}

const BossBattleRouteChildren: BossBattleRouteChildren = {
  BossBattleBattleIdRoute: BossBattleBattleIdRoute,
}

const BossBattleRouteWithChildren = BossBattleRoute._addFileChildren(
  BossBattleRouteChildren,
)

interface ExploreRouteChildren {
  ExploreSubjectIdRoute: typeof ExploreSubjectIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSubjectIdRoute: ExploreSubjectIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface FunGamesRouteChildren {
  FunGamesLogicRoute: typeof FunGamesLogicRoute
  FunGamesMemoryRoute: typeof FunGamesMemoryRoute
  FunGamesPatternRoute: typeof FunGamesPatternRoute
}

const FunGamesRouteChildren: FunGamesRouteChildren = {
  FunGamesLogicRoute: FunGamesLogicRoute,
  FunGamesMemoryRoute: FunGamesMemoryRoute,
  FunGamesPatternRoute: FunGamesPatternRoute,
}

const FunGamesRouteWithChildren = FunGamesRoute._addFileChildren(
  FunGamesRouteChildren,
)

interface KnowledgeArenaRouteChildren {
  KnowledgeArenaLobbyRoute: typeof KnowledgeArenaLobbyRoute
  KnowledgeArenaMatchRoute: typeof KnowledgeArenaMatchRoute
}

const KnowledgeArenaRouteChildren: KnowledgeArenaRouteChildren = {
  KnowledgeArenaLobbyRoute: KnowledgeArenaLobbyRoute,
  KnowledgeArenaMatchRoute: KnowledgeArenaMatchRoute,
}

const KnowledgeArenaRouteWithChildren = KnowledgeArenaRoute._addFileChildren(
  KnowledgeArenaRouteChildren,
)

interface ZiabotRouteChildren {
  ZiabotFlashcardsRoute: typeof ZiabotFlashcardsRoute
  ZiabotNotesRoute: typeof ZiabotNotesRoute
  ZiabotPracticeRoute: typeof ZiabotPracticeRoute
}

const ZiabotRouteChildren: ZiabotRouteChildren = {
  ZiabotFlashcardsRoute: ZiabotFlashcardsRoute,
  ZiabotNotesRoute: ZiabotNotesRoute,
  ZiabotPracticeRoute: ZiabotPracticeRoute,
}

const ZiabotRouteWithChildren =
  ZiabotRoute._addFileChildren(ZiabotRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BossBattleRoute: BossBattleRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FunGamesRoute: FunGamesRouteWithChildren,
  KnowledgeArenaRoute: KnowledgeArenaRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  ZiabotRoute: ZiabotRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CreatorExplainRoute: CreatorExplainRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
